apiVersion: v1
kind: ServiceAccount
metadata:
  name: crd-ipkeeper
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crd-ipkeeper
rules:
- apiGroups: [""]
  ## configmap用于创建分布式资源锁
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "patch", "update"]
- apiGroups: [""]
  ## configmap用于创建分布式资源锁
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["ipkeeper.generals.space"]
  ## 自定义类型资源也需要通过 rbac 赋予权限.
  resources: ["staticips"]
  verbs: ["get", "list", "watch", "create", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-ipkeeper
roleRef:
  name: crd-ipkeeper
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: crd-ipkeeper
  namespace: kube-system
  
---
## 由于 crd-ipkeeper 会监听 deployment/daemonset 等, 
## 然后可能创建并修改 StaticIP 资源, 所以必须要事先创建 CRD, 
## 同时在 RBAC 配置中添加上对 staticips 类型资源的访问权限
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  ## metadata.name = plural值 + group值
  name: staticips.ipkeeper.generals.space
spec:
  group: ipkeeper.generals.space
  version: v1
  names:
    kind: StaticIP
    plural: staticips
  scope: Namespaced

---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: crd-ipkeeper
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: crd-ipkeeper
  template:
    metadata:
      labels:
        app: crd-ipkeeper
        component: network
        type: infra
    spec:
      tolerations:
      - effect: NoSchedule
        operator: Exists
      serviceAccountName: crd-ipkeeper
      hostNetwork: true
      hostPID: true
      containers:
      - name: crd-ipkeeper
        image: registry.cn-hangzhou.aliyuncs.com/generals-kuber/crd-ipkeeper:0.0.38
        securityContext:
          privileged: true
          capabilities:
            add: ["NET_ADMIN", "SYS_PTRACE", "SYS_ADMIN"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NS
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - mountPath: /var/run
          name: socket
        - mountPath: /var/run/netns
          name: host-netns
      volumes:
      - name: socket
        hostPath:
          path: /var/run
      - name: host-netns
        hostPath:
          path: /var/run/netns
