/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	ipkeeperv1 "github.com/generals-space/crd-ipkeeper/pkg/apis/ipkeeper/v1"
	versioned "github.com/generals-space/crd-ipkeeper/pkg/client/clientset/versioned"
	internalinterfaces "github.com/generals-space/crd-ipkeeper/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/generals-space/crd-ipkeeper/pkg/client/listers/ipkeeper/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// StaticIPsInformer provides access to a shared informer and lister for
// StaticIPses.
type StaticIPsInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.StaticIPsLister
}

type staticIPsInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewStaticIPsInformer constructs a new informer for StaticIPs type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewStaticIPsInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredStaticIPsInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredStaticIPsInformer constructs a new informer for StaticIPs type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredStaticIPsInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IpkeeperV1().StaticIPses(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IpkeeperV1().StaticIPses(namespace).Watch(options)
			},
		},
		&ipkeeperv1.StaticIPs{},
		resyncPeriod,
		indexers,
	)
}

func (f *staticIPsInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredStaticIPsInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *staticIPsInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&ipkeeperv1.StaticIPs{}, f.defaultInformer)
}

func (f *staticIPsInformer) Lister() v1.StaticIPsLister {
	return v1.NewStaticIPsLister(f.Informer().GetIndexer())
}
