/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	ipkeeperv1 "github.com/generals-space/crd-ipkeeper/pkg/apis/ipkeeper/v1"
	versioned "github.com/generals-space/crd-ipkeeper/pkg/client/clientset/versioned"
	internalinterfaces "github.com/generals-space/crd-ipkeeper/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/generals-space/crd-ipkeeper/pkg/client/listers/ipkeeper/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// StaticIPInformer provides access to a shared informer and lister for
// StaticIPs.
type StaticIPInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.StaticIPLister
}

type staticIPInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewStaticIPInformer constructs a new informer for StaticIP type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewStaticIPInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredStaticIPInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredStaticIPInformer constructs a new informer for StaticIP type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredStaticIPInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IpkeeperV1().StaticIPs(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IpkeeperV1().StaticIPs(namespace).Watch(options)
			},
		},
		&ipkeeperv1.StaticIP{},
		resyncPeriod,
		indexers,
	)
}

func (f *staticIPInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredStaticIPInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *staticIPInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&ipkeeperv1.StaticIP{}, f.defaultInformer)
}

func (f *staticIPInformer) Lister() v1.StaticIPLister {
	return v1.NewStaticIPLister(f.Informer().GetIndexer())
}
