/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	ipkeeperv1 "github.com/generals-space/crd-ipkeeper/pkg/apis/ipkeeper/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeStaticIPses implements StaticIPsInterface
type FakeStaticIPses struct {
	Fake *FakeIpkeeperV1
	ns   string
}

var staticipsesResource = schema.GroupVersionResource{Group: "ipkeeper.generals.space", Version: "v1", Resource: "staticipses"}

var staticipsesKind = schema.GroupVersionKind{Group: "ipkeeper.generals.space", Version: "v1", Kind: "StaticIPs"}

// Get takes name of the staticIPs, and returns the corresponding staticIPs object, and an error if there is any.
func (c *FakeStaticIPses) Get(name string, options v1.GetOptions) (result *ipkeeperv1.StaticIPs, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(staticipsesResource, c.ns, name), &ipkeeperv1.StaticIPs{})

	if obj == nil {
		return nil, err
	}
	return obj.(*ipkeeperv1.StaticIPs), err
}

// List takes label and field selectors, and returns the list of StaticIPses that match those selectors.
func (c *FakeStaticIPses) List(opts v1.ListOptions) (result *ipkeeperv1.StaticIPsList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(staticipsesResource, staticipsesKind, c.ns, opts), &ipkeeperv1.StaticIPsList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &ipkeeperv1.StaticIPsList{ListMeta: obj.(*ipkeeperv1.StaticIPsList).ListMeta}
	for _, item := range obj.(*ipkeeperv1.StaticIPsList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested staticIPses.
func (c *FakeStaticIPses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(staticipsesResource, c.ns, opts))

}

// Create takes the representation of a staticIPs and creates it.  Returns the server's representation of the staticIPs, and an error, if there is any.
func (c *FakeStaticIPses) Create(staticIPs *ipkeeperv1.StaticIPs) (result *ipkeeperv1.StaticIPs, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(staticipsesResource, c.ns, staticIPs), &ipkeeperv1.StaticIPs{})

	if obj == nil {
		return nil, err
	}
	return obj.(*ipkeeperv1.StaticIPs), err
}

// Update takes the representation of a staticIPs and updates it. Returns the server's representation of the staticIPs, and an error, if there is any.
func (c *FakeStaticIPses) Update(staticIPs *ipkeeperv1.StaticIPs) (result *ipkeeperv1.StaticIPs, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(staticipsesResource, c.ns, staticIPs), &ipkeeperv1.StaticIPs{})

	if obj == nil {
		return nil, err
	}
	return obj.(*ipkeeperv1.StaticIPs), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeStaticIPses) UpdateStatus(staticIPs *ipkeeperv1.StaticIPs) (*ipkeeperv1.StaticIPs, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(staticipsesResource, "status", c.ns, staticIPs), &ipkeeperv1.StaticIPs{})

	if obj == nil {
		return nil, err
	}
	return obj.(*ipkeeperv1.StaticIPs), err
}

// Delete takes name of the staticIPs and deletes it. Returns an error if one occurs.
func (c *FakeStaticIPses) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(staticipsesResource, c.ns, name), &ipkeeperv1.StaticIPs{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeStaticIPses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(staticipsesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &ipkeeperv1.StaticIPsList{})
	return err
}

// Patch applies the patch and returns the patched staticIPs.
func (c *FakeStaticIPses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *ipkeeperv1.StaticIPs, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(staticipsesResource, c.ns, name, pt, data, subresources...), &ipkeeperv1.StaticIPs{})

	if obj == nil {
		return nil, err
	}
	return obj.(*ipkeeperv1.StaticIPs), err
}
