/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/generals-space/crd-ipkeeper/pkg/apis/ipkeeper/v1"
	scheme "github.com/generals-space/crd-ipkeeper/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// StaticIPsesGetter has a method to return a StaticIPsInterface.
// A group's client should implement this interface.
type StaticIPsesGetter interface {
	StaticIPses(namespace string) StaticIPsInterface
}

// StaticIPsInterface has methods to work with StaticIPs resources.
type StaticIPsInterface interface {
	Create(ctx context.Context, staticIPs *v1.StaticIPs, opts metav1.CreateOptions) (*v1.StaticIPs, error)
	Update(ctx context.Context, staticIPs *v1.StaticIPs, opts metav1.UpdateOptions) (*v1.StaticIPs, error)
	UpdateStatus(ctx context.Context, staticIPs *v1.StaticIPs, opts metav1.UpdateOptions) (*v1.StaticIPs, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.StaticIPs, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.StaticIPsList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.StaticIPs, err error)
	StaticIPsExpansion
}

// staticIPses implements StaticIPsInterface
type staticIPses struct {
	client rest.Interface
	ns     string
}

// newStaticIPses returns a StaticIPses
func newStaticIPses(c *IpkeeperV1Client, namespace string) *staticIPses {
	return &staticIPses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the staticIPs, and returns the corresponding staticIPs object, and an error if there is any.
func (c *staticIPses) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.StaticIPs, err error) {
	result = &v1.StaticIPs{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("staticipses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of StaticIPses that match those selectors.
func (c *staticIPses) List(ctx context.Context, opts metav1.ListOptions) (result *v1.StaticIPsList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.StaticIPsList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("staticipses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested staticIPses.
func (c *staticIPses) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("staticipses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a staticIPs and creates it.  Returns the server's representation of the staticIPs, and an error, if there is any.
func (c *staticIPses) Create(ctx context.Context, staticIPs *v1.StaticIPs, opts metav1.CreateOptions) (result *v1.StaticIPs, err error) {
	result = &v1.StaticIPs{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("staticipses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(staticIPs).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a staticIPs and updates it. Returns the server's representation of the staticIPs, and an error, if there is any.
func (c *staticIPses) Update(ctx context.Context, staticIPs *v1.StaticIPs, opts metav1.UpdateOptions) (result *v1.StaticIPs, err error) {
	result = &v1.StaticIPs{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("staticipses").
		Name(staticIPs.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(staticIPs).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *staticIPses) UpdateStatus(ctx context.Context, staticIPs *v1.StaticIPs, opts metav1.UpdateOptions) (result *v1.StaticIPs, err error) {
	result = &v1.StaticIPs{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("staticipses").
		Name(staticIPs.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(staticIPs).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the staticIPs and deletes it. Returns an error if one occurs.
func (c *staticIPses) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("staticipses").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *staticIPses) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("staticipses").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched staticIPs.
func (c *staticIPses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.StaticIPs, err error) {
	result = &v1.StaticIPs{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("staticipses").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
