apiVersion: v1
kind: Pod
metadata:
  name: devops
  annotations:
    ipkeeper.generals.space/ip_address: 172.16.91.140/24
    ipkeeper.generals.space/gateway: 172.16.91.2
spec:
  containers:
  - name: devops
    image: registry.cn-hangzhou.aliyuncs.com/generals-space/centos7:devops
    command: ["tail", "-f", "/etc/os-release"]
    securityContext:
      privileged: false
      capabilities:
        add: ["NET_ADMIN"]
  ## 允许在master节点部署
  tolerations:
    ## 这一段表示pod需要容忍拥有master角色的node们,
    ## 且这个污点的效果是 NoSchedule.
    ## 因为key, operator, value, effect可以唯一确定一个污点对象(Taint).
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
